name: Docker Image CI

env:
  DOCKER_REG: registry.cn-shanghai.aliyuncs.com/opar/foodie-web
  REG: registry.cn-shanghai.aliyuncs.com
  CONTAINER_NAME: foodie-web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: set IMAGE_TAG env
      run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF##*/}-$(git rev-parse --short "$GITHUB_SHA")" 
    - name: Login Docker
      run: 
        echo "${{ secrets.PASSWORD }}" | docker login $REG -u "${{ secrets.USERNAME }}" --password-stdin
    - name: Build the Docker image
      run:
        docker build . --file Dockerfile --tag image
    - name: Push Image
      run: |
        echo DOCKER_REG=$DOCKER_REG
        echo IMAGE_TAG=$IMAGE_TAG
        docker tag image $DOCKER_REG:$IMAGE_TAG
        docker push $DOCKER_REG:$IMAGE_TAG
    - uses: appleboy/ssh-action@v0.0.7
      name: deploy docker image
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        envs: CONTAINER_NAME, DOCKER_REG, IMAGE_TAG
        script: |
          echo DOCKER_REG=$DOCKER_REG
          echo IMAGE_TAG=$IMAGE_TAG
          echo CONTAINER_NAME=$CONTAINER_NAME
          if [ $(docker ps -a | grep -c $CONTAINER_NAME) -gt 0 ]; then docker stop $CONTAINER_NAME;docker rm $CONTAINER_NAME;fi
          docker run --name $CONTAINER_NAME -d -p 4000:4000 $DOCKER_REG:$IMAGE_TAG
  
